import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './agent-hierarchy.css';
import TelemetryGuide from './TelemetryGuide.jsx';
import './telemetry-guide.css';

const navItems = [
  { id: 'overview', label: 'Overview', icon: '◫' },
  { id: 'agents', label: 'Agent inventory', icon: '◇' },
  { id: 'approvals', label: 'Approvals', icon: '✓' },
  { id: 'policies', label: 'Policies', icon: '⛨' },
  { id: 'activity', label: 'Audit log', icon: '≋' }
];
const initialForm = { name: '', team: '', tools: '', id: '', companyId: '', companyIdValue: '', companyName: '', agentType: 'general', framework: 'unknown', model: '', version: '', parentId: '', runtimeUrl: '', riskTier: 'unassessed', dataClass: 'internal', autonomy: 'assistive', scope: '', agentId: '*', actionType: '*', resourcePattern: '*', effect: 'require_approval', priority: '100' };
const newAgentId = agents => { const used = new Set(agents.map(agent => String(agent.id))); let id; do { id = String(Math.floor(1000 + Math.random() * 9000)); } while (used.has(id)); return id; };

function Home() {
  return <main className="react-home"><section className="home-card"><div className="home-brand"><span className="home-mark">◈</span><span>agentguard</span></div><div className="home-copy"><span className="home-eyebrow">AI agent control plane</span><h1>Operate every agent with confidence.</h1><p>Centralize agent inventory, approvals, policies, and audit activity in one secure workspace.</p><a className="home-login" href="/auth/login">Continue with Google <span>→</span></a></div><div className="home-features"><div><b>Governance</b><small>Enforce policies before sensitive actions run.</small></div><div><b>Visibility</b><small>Monitor health and activity across your fleet.</small></div><div><b>Accountable</b><small>Keep a complete audit trail for every decision.</small></div></div></section></main>;
}

async function request(url, options) {
  const response = await fetch(url, { cache: 'no-store', ...options, headers: { ...(options?.body ? { 'Content-Type': 'application/json' } : {}), ...options?.headers } });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.error || `Request failed (${response.status})`);
  return payload;
}

function App() {
  const [auth, setAuth] = useState(null);
  const [data, setData] = useState({ companies: [], agents: [], policies: [], approvals: [], events: [] });
  const [view, setView] = useState(location.hash.slice(1).split('/')[0] || 'overview');
  const [busy, setBusy] = useState(false);
  const [updatedAt, setUpdatedAt] = useState(null);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const [dialog, setDialog] = useState('');
  const [onboarding, setOnboarding] = useState(null);
  const [form, setForm] = useState(initialForm);
  const [selectedAgent, setSelectedAgent] = useState(null);
  const [query, setQuery] = useState('');
  const [fleetOpen, setFleetOpen] = useState(false);
  const [connectAgent, setConnectAgent] = useState(null);

  useEffect(() => { request('/api/session').then(setAuth).catch(() => setAuth({ authenticated: false })); }, []);

  const refresh = useCallback(async (quiet = false) => {
    if (!quiet) setBusy(true);
    try {
      const latest = await request('/api/dashboard');
      setData({ companies: latest.companies || [], agents: latest.agents || [], policies: latest.policies || [], approvals: latest.approvals || [], events: latest.events || [] });
      const [route, agentId] = location.hash.slice(1).split('/');
      if (route === 'agents' && agentId) {
        const selected = latest.agents.find(agent => agent.id === decodeURIComponent(agentId));
        if (selected) { setSelectedAgent(selected); setView('agent-detail'); }
      }
      setUpdatedAt(new Date()); setError('');
    } catch (err) { setError(err.message); }
    finally { if (!quiet) setBusy(false); }
  }, []);

  useEffect(() => {
    refresh();
    const timer = setInterval(() => refresh(true), 10000);
    const onHash = () => {
      const [route, agentId] = location.hash.slice(1).split('/');
      if (route === 'agents' && agentId) {
        const agent = data.agents.find(item => item.id === decodeURIComponent(agentId));
        if (agent) { setSelectedAgent(agent); setView('agent-detail'); }
        else setView('agents');
      } else { setSelectedAgent(null); setView(route || 'overview'); }
    };
    window.addEventListener('hashchange', onHash);
    return () => { clearInterval(timer); window.removeEventListener('hashchange', onHash); };
  }, [refresh, data.agents]);

  const notify = message => { setToast(message); window.setTimeout(() => setToast(''), 2800); };
  const navigate = id => { setSelectedAgent(null); setView(id); history.replaceState(null, '', `#${id}`); };
  const goToAgent = agent => { setSelectedAgent(agent); setView('agent-detail'); history.replaceState(null, '', `#agents/${encodeURIComponent(agent.id)}`); };
  const mutate = async (url, options, success) => {
    try { await request(url, options); await refresh(true); notify(success); }
    catch (err) { notify(err.message); }
  };
  const decide = (approval, decision) => mutate(`/api/approvals/${encodeURIComponent(approval.id)}/${decision}`, { method: 'POST', body: JSON.stringify({ rationale: '' }) }, decision === 'approve' ? 'Approval recorded in audit log' : 'Request denied and logged');
  const togglePolicy = policy => mutate(`/api/policies/${policy.id}`, { method: 'PATCH', body: JSON.stringify({ enabled: !policy.enabled }) }, `Policy ${policy.enabled ? 'paused' : 'enabled'}`);

  const openDialog = kind => { setForm(kind === 'agent' ? { ...initialForm, id: '' } : initialForm); setDialog(kind); };
  const submitDialog = async event => {
    event.preventDefault();
    let selectedCompanyId = form.companyId;
    if (dialog === 'agent' && form.companyId === '__new__') {
      const company = await request('/api/companies', { method: 'POST', body: JSON.stringify({ name: form.companyName }) });
      selectedCompanyId = company.id;
    }
    const body = (dialog === 'agent' || dialog === 'edit-agent')
      ? { id: form.id, companyId: selectedCompanyId, name: form.name, agentType: form.agentType, framework: form.framework, model: form.model, version: form.version, team: form.team, tools: form.tools.split(',').map(x => x.trim()).filter(Boolean), parentId: form.parentId || null, runtimeUrl: form.runtimeUrl || '', riskTier: form.riskTier, dataClass: form.dataClass, autonomy: form.autonomy }
      : dialog === 'policy'
        ? { name: form.name, scope: form.scope, agentId: form.agentId, actionType: form.actionType, resourcePattern: form.resourcePattern, effect: form.effect, priority: Number(form.priority), enabled: true }
        : { agentId: form.agentId, action: form.action, risk: form.risk };
    const editing = dialog === 'edit-policy', editingAgent = dialog === 'edit-agent';
    const endpoint = dialog === 'agent' ? '/api/agents' : editingAgent ? `/api/agents/${encodeURIComponent(form.id)}` : isPolicyDialog(dialog) ? (editing ? `/api/policies/${encodeURIComponent(form.id)}` : '/api/policies') : '/api/approvals';
    try { const saved = await request(endpoint, { method: editing || editingAgent ? 'PATCH' : 'POST', body: JSON.stringify(body) }); setDialog(''); await refresh(true); if (dialog === 'agent') setOnboarding(saved); else notify(editingAgent ? 'Agent updated' : editing ? 'Policy updated' : 'Saved successfully'); }
    catch (err) { notify(err.message); }
  };

  const agentById = useMemo(() => Object.fromEntries(data.agents.map(agent => [agent.id, agent])), [data.agents]);
  const healthy = data.agents.filter(agent => !agent.archived && agent.status === 'healthy').length;
  const blocked = data.events.filter(event => event.kind === 'block').length;
  const filteredEvents = data.events.filter(event => `${event.message} ${event.actor} ${event.agentId || ''}`.toLowerCase().includes(query.toLowerCase()));
  const activeView = view === 'agent-detail' ? 'agents' : view;

  if (auth === null) return <div className="auth-loading">Loading AgentGuard…</div>;
  if (!auth.authenticated) return <Home />;

  return <div className="shell">
    <aside className="sidebar">
      <button className="brand" onClick={() => navigate('overview')}><span className="brand-mark"><ShieldIcon /></span><span>agentguard<small>CONTROL PLANE</small></span></button>
      <div className="workspace"><div className="workspace-avatar">A</div><div><small>WORKSPACE</small><b>Acme Operations</b></div><span className="chevron">⌄</span></div>
      <div className="nav-caption">MONITOR</div>
      <nav>{navItems.map(item => <button key={item.id} className={`nav-item ${activeView === item.id ? 'selected' : ''}`} onClick={() => navigate(item.id)}><span className="nav-icon">{item.icon}</span>{item.label}{item.id === 'approvals' && data.approvals.length > 0 && <span className="nav-count">{data.approvals.length}</span>}</button>)}<button className="nav-item fleet-nav" onClick={() => setFleetOpen(true)}><span className="nav-icon">＋</span>Connect fleet</button></nav>
      <div className="sidebar-bottom"><div className="security-card"><span className="secure-icon">◈</span><div><b>Governance active</b><small>Policies enforced in real time</small></div><i /></div><div className="user-menu"><div className="user-card"><span className="user-avatar">AS</span><span><b>Abhimanyu S.</b><small>Workspace admin</small></span></div><a className="logout-button" href="/auth/logout">↪ <span>Sign out</span></a></div></div>
    </aside>

    <main className="main-area">
      <header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span className="crumb-sep">/</span><b>{selectedAgent?.name || navItems.find(item => item.id === activeView)?.label || 'Overview'}</b></div><div className="top-actions"><span className={`connection ${error ? 'disconnected' : ''}`}><i />{error ? 'Connection issue' : 'All systems operational'}</span><button className={`icon-button ${busy ? 'spinning' : ''}`} title="Refresh dashboard" onClick={() => refresh()} aria-label="Refresh dashboard">↻</button><button className="help-button">? <span>Help & support</span></button><span className="top-avatar">AS</span></div></header>
      {selectedAgent && <button className="button secondary floating-edit" onClick={()=>{setForm({...initialForm,...selectedAgent,tools:(selectedAgent.tools||[]).join(',')});setDialog('edit-agent')}}>✎ Edit agent</button>}
      {error && <div className="error-banner"><span>Unable to refresh AgentGuard data: {error}</span><button onClick={() => refresh()}>Retry</button></div>}

      {view === 'overview' && <Overview data={data} healthy={healthy} blocked={blocked} agentById={agentById} navigate={navigate} goToAgent={goToAgent} decide={decide} />}
      {view === 'agents' && <><AgentInventory agents={data.agents} goToAgent={goToAgent} onAdd={() => openDialog('agent')} onConnect={setConnectAgent} /><TelemetryGuide /></>}
      {view === 'agent-detail' && selectedAgent && <AgentDetails agent={{...(agentById[selectedAgent.id] || selectedAgent), parentAgent: data.agents.find(item => item.id === (agentById[selectedAgent.id] || selectedAgent).parentId)}} events={data.events.filter(event => event.agentId === selectedAgent.id)} policies={data.policies.filter(policy => policy.agentId === selectedAgent.id || policy.agentId === '*')} onBack={() => navigate('agents')} onConnect={setConnectAgent} onArchive={async agent => { await mutate(`/api/agents/${encodeURIComponent(agent.id)}`, { method: 'PATCH', body: JSON.stringify({ archived: !agent.archived }) }, agent.archived ? 'Agent restored' : 'Agent archived'); setSelectedAgent({ ...agent, archived: !agent.archived, status: agent.archived ? 'registered' : 'archived' }); }} />}
      {view === 'approvals' && <Approvals approvals={data.approvals} agentById={agentById} decide={decide} onAdd={() => openDialog('approval')} />}
      {view === 'policies' && <Policies policies={data.policies} agentById={agentById} onToggle={togglePolicy} onEdit={policy => { setForm({ ...initialForm, ...policy, priority: String(policy.priority) }); setDialog('edit-policy'); }} onAdd={() => openDialog('policy')} />}
      {view === 'activity' && <Activity events={filteredEvents} query={query} setQuery={setQuery} agentById={agentById} />}

      <footer className="page-footer"><span>AgentGuard Control Plane <b>v1.0</b></span><span>{updatedAt ? `Last synced ${updatedAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Waiting for data'}</span></footer>
    </main>
    {dialog === 'edit-agent' && selectedAgent && <EditAgentDialog agent={selectedAgent} agents={data.agents} companies={data.companies} onClose={() => setDialog('')} onSaved={async () => { setDialog(''); await refresh(true); notify('Agent updated'); }} />}
    {dialog && dialog !== 'edit-agent' && <Dialog kind={dialog} form={form} setForm={setForm} agents={data.agents} companies={data.companies} onClose={() => setDialog('')} onSubmit={submitDialog} />}
    {onboarding && <Onboarding agent={onboarding} onClose={() => setOnboarding(null)} />}
    {fleetOpen && <FleetWizard agents={data.agents} onClose={() => setFleetOpen(false)} onComplete={async () => { setFleetOpen(false); await refresh(true); notify('Fleet registered. Connect a telemetry source to monitor activity.'); }} />}
    {connectAgent && <ManagedConnectionDialog agent={connectAgent} onClose={() => setConnectAgent(null)} onConnected={async message => { setConnectAgent(null); await refresh(true); notify(message); }} />}
    {toast && <div className="toast"><span>✓</span>{toast}</div>}
  </div>;
}

function isPolicyDialog(kind){return kind==='policy'||kind==='edit-policy'}
function ShieldIcon(){return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 2 27 6v8c0 7.2-4.6 12.4-11 16C9.6 26.4 5 21.2 5 14V6l11-4Z" fill="currentColor"/><path d="m11 16 3.2 3.2 6.8-7" fill="none" stroke="#101a2e" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function PageHeading({eyebrow,title,description,action}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function Metric({label,value,detail,icon,tone='blue'}){return <div className="metric-card"><div className={`metric-icon ${tone}`}>{icon}</div><div className="metric-copy"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div><div className={`metric-spark ${tone}`}><i/><i/><i/><i/><i/><i/><i/></div></div>}
function Overview({data,healthy,blocked,agentById,navigate,goToAgent,decide}){
  const latest=data.events.slice(0,5);const mix=[{label:'Allowed',count:data.events.filter(event=>event.kind==='action').length,tone:'green'},{label:'Approval',count:data.events.filter(event=>event.kind==='approval').length,tone:'amber'},{label:'Blocked',count:blocked,tone:'red'}];const total=mix.reduce((sum,item)=>sum+item.count,0)||1;
  return <div className="page-content"><PageHeading eyebrow="SECURITY OVERVIEW" title="Agent operations" description="Monitor your AI workforce, enforce guardrails, and review sensitive actions." action={<button className="button secondary" onClick={()=>navigate('activity')}><span>↓</span> Export activity</button>} />
    <div className="metrics-grid"><Metric label="Connected agents" value={healthy} detail={`${data.agents.filter(agent=>!agent.archived).length} active in workspace`} icon="◇" tone="blue"/><Metric label="Awaiting approval" value={data.approvals.length} detail={data.approvals.length?'Human review required':'Queue is clear'} icon="◷" tone="amber"/><Metric label="Policy blocks" value={blocked} detail="Recorded in audit history" icon="⊘" tone="red"/><Metric label="Active policies" value={data.policies.filter(policy=>policy.enabled).length} detail={`${data.policies.length} total policies`} icon="⛨" tone="green"/></div>
    <div className="overview-grid"><section className="panel agent-panel"><div className="panel-header"><div><h2>Agent inventory</h2><p>Live connections across your workspace</p></div><button className="text-button" onClick={()=>navigate('agents')}>View all <span>→</span></button></div><div className="agent-list">{data.agents.length?data.agents.slice(0,5).map(agent=><AgentRow key={agent.id} agent={agent} onClick={()=>goToAgent(agent)}/>):<Empty icon="◇" title="No agents connected" message="Register an agent or connect an integration to get started."/>}</div></section>
      <section className="panel activity-mix"><div className="panel-header"><div><h2>Activity overview</h2><p>Events recorded in this workspace</p></div><button className="text-button" onClick={()=>navigate('activity')}>Audit log <span>→</span></button></div><div className="mix-body"><div className="donut-wrap"><div className="donut" style={{background:`conic-gradient(#35bc91 0 ${mix[0].count/total*100}%,#e9ad49 ${mix[0].count/total*100}% ${(mix[0].count+mix[1].count)/total*100}%,#df6170 ${(mix[0].count+mix[1].count)/total*100}% 100%)`}}><div><b>{data.events.length}</b><small>EVENTS</small></div></div></div><div className="mix-legend">{mix.map(item=><div key={item.label}><span><i className={item.tone}/>{item.label}</span><b>{item.count}</b></div>)}</div></div><div className="mix-foot"><span>Retention window</span><b>Local event store</b></div></section>
      <section className="panel approval-panel"><div className="panel-header"><div><h2>Approval queue <span className="count-badge">{data.approvals.length}</span></h2><p>Sensitive agent actions awaiting your review</p></div><button className="text-button" onClick={()=>navigate('approvals')}>Open queue <span>→</span></button></div>{data.approvals.length?<div className="approval-list">{data.approvals.slice(0,3).map(approval=><div className="approval-row" key={approval.id}><div className="approval-avatar">{(agentById[approval.agentId]?.name||'?').slice(0,1).toUpperCase()}</div><div className="approval-info"><b>{agentById[approval.agentId]?.name||'Unknown agent'}</b><span>{approval.action}</span><small>{approval.risk} · {timeAgo(approval.createdAt)}</small></div><div className="approval-actions"><button className="button small secondary" onClick={()=>decide(approval,'deny')}>Deny</button><button className="button small primary" onClick={()=>decide(approval,'approve')}>Approve</button></div></div>)}</div>:<Empty icon="✓" title="All caught up" message="New sensitive actions will appear here for review."/>}</section>
      <section className="panel event-panel"><div className="panel-header"><div><h2>Recent activity</h2><p>Latest events across monitored agents</p></div><button className="text-button" onClick={()=>navigate('activity')}>Full log <span>→</span></button></div>{latest.length?<div className="timeline">{latest.map(event=><EventRow key={event.id} event={event} agent={agentById[event.agentId]}/>)}</div>:<Empty icon="≋" title="No activity yet" message="Agent actions and policy decisions will be recorded here."/>}</section>
    </div>
  </div>;
}
function AgentStatus({agent,large=false}){const label=agent.archived?'Archived':agent.status!=='healthy'?'Registered':agent.runtimeStatus==='running'?'Running':agent.runtimeStatus==='failed'?'Failed':agent.runtimeStatus==='idle'||agent.runtimeStatus==='waiting'?'Idle':'Connected';const tone=agent.archived?'archived':agent.runtimeStatus==='running'?'running':agent.runtimeStatus==='failed'?'failed':agent.status==='healthy'?'healthy':'';return <span className={`status ${tone} ${large?'large':''}`} title={agent.connection?.lastError||''}><i/>{label}</span>}
function AgentRow({agent,onClick}){return <button className="agent-row" onClick={onClick}><span className="agent-avatar">{agent.name.slice(0,1).toUpperCase()}</span><span className="agent-main"><b>{agent.name}</b><small>{agent.team} <i>·</i> {agent.tools?.length||0} tools</small></span><AgentStatus agent={agent}/><span className="row-chevron">›</span></button>}
function AgentInventory({agents,goToAgent,onAdd,onConnect}){
  const[filter,setFilter]=useState('all');
  const matches=agent=>filter==='all'?!agent.archived:filter==='connected'?agent.status==='healthy':filter==='running'?agent.status==='healthy'&&agent.runtimeStatus==='running':filter==='idle'?agent.status==='healthy'&&['idle','waiting'].includes(agent.runtimeStatus):agent.status===filter;
  const visible=agents.filter(matches);
  const children=agents.filter(agent=>agent.parentId&&!agent.archived).length;
  const standalone=agents.filter(agent=>!agent.parentId&&!agent.archived).length;
  const parentName=id=>agents.find(item=>item.id===id)?.name||'Unknown parent';
  const count=id=>id==='all'?agents.filter(agent=>!agent.archived).length:agents.filter(agent=>id==='connected'?agent.status==='healthy':id==='running'?agent.runtimeStatus==='running':id==='idle'?agent.status==='healthy'&&['idle','waiting'].includes(agent.runtimeStatus):agent.status===id).length;
  return <div className="page-content"><PageHeading eyebrow="WORKSPACE" title="Agent inventory" description="Register an agent, add its runtime URL, then start the managed connection with one click." action={<button className="button primary" onClick={onAdd}><span>＋</span> Register agent</button>}/><div className="agent-type-summary"><div><b>{standalone}</b><span>Standalone agents</span></div><div><b>{children}</b><span>Child / sub-agents</span></div></div><section className="panel data-panel"><div className="table-toolbar"><div className="segmented">{[['all','Active agents'],['connected','Connected'],['running','Running'],['idle','Idle'],['registered','Registered'],['archived','Archived']].map(([id,label])=><button className={filter===id?'active':''} key={id} onClick={()=>setFilter(id)}>{label}<span>{count(id)}</span></button>)}</div><span className="toolbar-hint">{agents.filter(agent=>!agent.archived).length} active agents in workspace</span></div><div className="data-table"><div className="table-head agent-columns"><span>AGENT</span><span>TYPE / PARENT</span><span>CONNECTED TOOLS</span><span>STATUS</span><span/></div>{visible.map(agent=><div className={`table-row agent-columns ${agent.archived?'archived-row':''}`} key={agent.id}><button className="table-agent" onClick={()=>goToAgent(agent)}><span className="agent-avatar">{agent.name.slice(0,1).toUpperCase()}</span><b>{agent.name}</b></button><span className="agent-type-cell"><i className={`agent-type-pill ${agent.parentId?'child':'standalone'}`}>{agent.parentId?'Child agent':'Standalone'}</i>{agent.parentId&&<small>↳ {parentName(agent.parentId)}</small>}</span><span className="tool-chips">{agent.tools?.length?agent.tools.slice(0,3).map(tool=><i key={tool}>{tool}</i>):<em>No tools listed</em>}{agent.tools?.length>3&&<i>+{agent.tools.length-3}</i>}</span><AgentStatus agent={agent}/>{!agent.archived?<button className={`button small ${agent.status==='healthy'?'secondary':'primary'}`} onClick={()=>onConnect(agent)}>{agent.status==='healthy'?'Manage':'Start'}</button>:<button className="more-button" onClick={()=>goToAgent(agent)}>View</button>}</div>)}{!visible.length&&<Empty icon="◇" title="No matching agents" message="Try another filter or register an agent."/>}</div></section></div>
}
function AgentDetails({agent,events,policies,onBack,onArchive,onConnect}){return <div className="page-content"><button className="back-button" onClick={onBack}>← Agent inventory</button><PageHeading eyebrow="AGENT PROFILE" title={agent.name} description={`${agent.team} · Agent ID ${agent.id} · Registered ${new Date(agent.createdAt).toLocaleDateString()}`} action={<div className="detail-actions"><span className={`agent-type-pill large ${agent.parentId?'child':'standalone'}`}>{agent.parentId?`Child agent · ${agent.parentAgent?.name||'Parent assigned'}`:'Standalone agent'}</span><span className={`status large ${agent.archived?'archived':agent.status==='healthy'?'healthy':''}`}><i/>{agent.archived?'Archived':agent.status==='healthy'?'Connected':'Registered'}</span>{!agent.archived&&<button className={`button ${agent.status==='healthy'?'secondary':'primary'}`} onClick={()=>onConnect(agent)}>{agent.status==='healthy'?'Manage connection':'Start connection'}</button>}<button className="button secondary" onClick={()=>onArchive(agent)}>{agent.archived?'Restore agent':'Archive agent'}</button></div>}/>{agent.connection?.lastError&&<div className="error-banner"><span>Connection failed: {agent.connection.lastError}</span></div>}<div className="detail-grid"><section className="panel"><div className="panel-header"><div><h2>Access footprint</h2><p>Tools this agent may use</p></div><span className="subtle-icon">◇</span></div><div className="tool-grid">{agent.tools?.length?agent.tools.map(tool=><div className="tool-card" key={tool}><span>▧</span><b>{tool}</b><small>Connected tool</small></div>):<Empty title="No tools configured" message="Tools will appear when the agent registers them."/>}</div></section><section className="panel"><div className="panel-header"><div><h2>Effective policies</h2><p>Controls applying to this agent</p></div></div><div className="detail-policy-list">{policies.length?policies.map(policy=><div className="detail-policy" key={policy.id}><span className={`policy-effect ${policy.effect}`}>{policy.effect.replace('_',' ')}</span><div><b>{policy.name}</b><small>{policy.actionType} · {policy.resourcePattern||'*'}</small></div><span className={`policy-enabled ${policy.enabled?'on':''}`}>{policy.enabled?'Enabled':'Paused'}</span></div>):<Empty title="No policies apply" message="This agent currently has no matching guardrails."/>}</div></section><section className="panel detail-events"><div className="panel-header"><div><h2>Agent audit trail</h2><p>Recent events linked to this agent</p></div></div><div className="timeline">{events.length?events.slice(0,10).map(event=><EventRow key={event.id} event={event}/>):<Empty title="No events recorded" message="Agent activity will appear here."/>}</div></section></div></div>}
function Approvals({approvals,agentById,decide,onAdd}){return <div className="page-content"><PageHeading eyebrow="HUMAN-IN-THE-LOOP" title="Approvals" description="Review and authorize sensitive actions before an agent proceeds." action={<button className="button secondary" onClick={onAdd}><span>＋</span> Create request</button>}/><section className="panel data-panel"><div className="table-toolbar"><div><b className="toolbar-title">Pending decisions</b><span className="count-badge">{approvals.length}</span></div><span className="toolbar-hint">Decisions are recorded in the audit log</span></div>{approvals.length?<div className="approval-table">{approvals.map(approval=><article className="approval-card" key={approval.id}><div className="approval-avatar big">{(agentById[approval.agentId]?.name||'?').slice(0,1).toUpperCase()}</div><div className="approval-detail"><div className="approval-title"><b>{agentById[approval.agentId]?.name||'Unknown agent'}</b><span className="risk-label">◈ {approval.risk}</span></div><h3>{approval.action}</h3><p>Resource <code>{approval.resource||'Unspecified'}</code>{approval.actionType&&<> · Action type <code>{approval.actionType}</code></>}</p><small>Requested {timeAgo(approval.createdAt)}{approval.policyId&&` · Policy ${approval.policyId.slice(0,8)}`}</small></div><div className="approval-decision"><button className="button secondary" onClick={()=>decide(approval,'deny')}>Deny</button><button className="button primary" onClick={()=>decide(approval,'approve')}>Approve action</button></div></article>)}</div>:<Empty icon="✓" title="No pending approvals" message="You're all caught up. Actions requiring review will appear here."/>}</section></div>}
function Policies({policies,agentById,onToggle,onEdit,onAdd}){return <div className="page-content"><PageHeading eyebrow="GOVERNANCE" title="Policies & guardrails" description="Define which actions agents can take, which require approval, and which are blocked." action={<button className="button primary" onClick={onAdd}><span>＋</span> Create policy</button>}/><div className="policy-summary"><div><span className="summary-dot green"/><b>{policies.filter(policy=>policy.enabled&&policy.effect==='allow').length}</b><small>Allow</small></div><div><span className="summary-dot amber"/><b>{policies.filter(policy=>policy.enabled&&policy.effect==='require_approval').length}</b><small>Require approval</small></div><div><span className="summary-dot red"/><b>{policies.filter(policy=>policy.enabled&&policy.effect==='block').length}</b><small>Block</small></div><div><span className="summary-dot gray"/><b>{policies.filter(policy=>!policy.enabled).length}</b><small>Paused</small></div></div><section className="panel data-panel"><div className="table-toolbar"><b className="toolbar-title">Policy rules <span className="count-badge">{policies.length}</span></b><span className="toolbar-hint">Higher priority rules take precedence</span></div>{policies.length?<div className="policy-table">{policies.slice().sort((a,b)=>(b.priority||0)-(a.priority||0)).map(policy=><article className={`policy-card ${!policy.enabled?'paused':''}`} key={policy.id}><div className={`policy-emblem ${policy.effect}`}>{policy.effect==='block'?'⊘':policy.effect==='allow'?'✓':'◷'}</div><div className="policy-main"><div className="policy-name"><h3>{policy.name}</h3><span className={`effect-pill ${policy.effect}`}>{policy.effect.replace('_',' ')}</span></div><p>{policy.scope}</p><div className="policy-meta"><span>Agent <b>{policy.agentId==='*'?'All agents':agentById[policy.agentId]?.name||'Unknown'}</b></span><span>Action <b>{policy.actionType}</b></span><span>Resource <b>{policy.resourcePattern||'*'}</b></span><span>Priority <b>{policy.priority??100}</b></span></div></div><div className="policy-controls"><button className="text-button" onClick={()=>onEdit(policy)}>Edit</button><button className={`switch ${policy.enabled?'on':''}`} aria-label={`${policy.enabled?'Pause':'Enable'} ${policy.name}`} onClick={()=>onToggle(policy)}><i/></button></div></article>)}</div>:<Empty icon="⛨" title="No policies configured" message="Create a rule to put guardrails around agent actions."/>}</section></div>}
function Activity({events,query,setQuery,agentById}){const kinds=[...new Set(events.map(event=>event.kind))];return <div className="page-content"><PageHeading eyebrow="AUDIT & COMPLIANCE" title="Activity log" description="A chronological record of agent actions and governance decisions." action={<span className="audit-retention">◉ Local event store</span>}/><section className="panel data-panel"><div className="table-toolbar activity-toolbar"><label className="search-box"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search events, agents, actors…"/></label><span className="toolbar-hint">{events.length} events shown</span></div><div className="audit-list">{events.length?events.map(event=><EventRow key={event.id} event={event} agent={agentById[event.agentId]} expanded/>):<Empty title={kinds.length?'No matching events':'No activity recorded'} message={kinds.length?'Try adjusting your search.':'Agent activity will appear here as it happens.'}/>}</div></section></div>}
function EventRow({event,agent,expanded=false}){const tone=event.kind==='block'?'red':event.kind==='approval'?'amber':'green';const task=event.currentTask||event.metadata?.currentTask;const status=event.status||event.metadata?.status;return <article className={`event-row ${expanded?'expanded':''}`}><span className={`event-symbol ${tone}`}>{event.kind==='block'?'⊘':event.kind==='approval'?'◷':'✓'}</span><div className="event-content"><b>{event.message}</b><span>{agent?.name||event.agentId||event.actor||'System'}{status&&` · ${status}`}{event.policyId&&` · policy ${event.policyId.slice(0,8)}`}{event.resource&&` · ${event.resource}`}</span>{expanded&&task&&<small>Task: {task}</small>}{expanded&&event.rationale&&<small>Decision note: {event.rationale}</small>}</div><div className="event-time"><b>{timeAgo(event.createdAt)}</b><small>{new Date(event.createdAt).toLocaleString()}</small></div></article>}
function Empty({icon='≋',title,message}){return <div className="empty-state"><span>{icon}</span><b>{title}</b><p>{message}</p></div>}
function Dialog({kind,form,setForm,agents,companies=[],onClose,onSubmit}){const set=(key,value)=>setForm(current=>({...current,[key]:value}));const isAgent=kind==='agent',isPolicy=kind==='policy'||kind==='edit-policy';const title=isAgent?'Register agent':isPolicy?(kind==='edit-policy'?'Edit policy':'Create policy'):'Create approval request';return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><form className="modal" onSubmit={onSubmit}><div className="modal-head"><div><span className="eyebrow">WORKSPACE CONFIGURATION</span><h2>{title}</h2></div><button type="button" className="close-button" onClick={onClose}>×</button></div><div className="modal-body">
{isAgent&&<><Field label="Company / tenant"><select required value={form.companyId} onChange={event=>set('companyId',event.target.value)}><option value="" disabled>Select a company</option>{companies.map(company=><option key={company.id} value={company.id}>{company.name}</option>)}<option value="__new__">＋ Create new company</option></select></Field>{form.companyId==='__new__'&&<Field label="New company name" hint="AgentGuard will create the internal tenant identifier automatically"><input required value={form.companyName} onChange={event=>set('companyName',event.target.value)} placeholder="e.g. IPO Research Co."/></Field>}</>}
{isAgent&&<><div className="connect-intro"><span>✦</span><div><b>Register an agent with AgentGuard</b><small>Add its connection API now for one-click activation.</small></div></div><Field label="Agent ID" hint="A unique four-digit number is assigned when you register"><input value="Generated automatically" readOnly /></Field><Field label="Agent name"><input required value={form.name} onChange={event=>set('name',event.target.value)} placeholder="e.g. Invoice Reconciliation"/></Field><Field label="Team or owner"><input required value={form.team} onChange={event=>set('team',event.target.value)} placeholder="e.g. Finance Operations"/></Field><Field label="Agent API URL" hint="Optional now; required when Start is clicked"><input type="url" value={form.runtimeUrl} onChange={event=>set('runtimeUrl',event.target.value)} placeholder="http://localhost:8000/api/agentguard/connect"/></Field><Field label="Parent system" hint="Optional; use for multi-agent systems"><select value={form.parentId} onChange={event=>set('parentId',event.target.value)}><option value="">Standalone agent</option>{agents.filter(agent=>agent.companyId===form.companyId).map(agent=><option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></Field><div className="field-grid"><Field label="Risk tier"><select value={form.riskTier} onChange={event=>set('riskTier',event.target.value)}><option value="unassessed">Unassessed</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></Field><Field label="Autonomy"><select value={form.autonomy} onChange={event=>set('autonomy',event.target.value)}><option value="assistive">Assistive</option><option value="supervised">Supervised</option><option value="autonomous">Autonomous</option></select></Field></div><Field label="Data classification"><select value={form.dataClass} onChange={event=>set('dataClass',event.target.value)}><option value="public">Public</option><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></select></Field><Field label="Connected tools" hint="Comma-separated"><input value={form.tools} onChange={event=>set('tools',event.target.value)} placeholder="NetSuite, Gmail"/></Field></>}
  {isPolicy&&<><Field label="Policy name"><input required value={form.name} onChange={event=>set('name',event.target.value)} placeholder="e.g. Require approval for external email"/></Field><Field label="Scope description"><input required value={form.scope} onChange={event=>set('scope',event.target.value)} placeholder="Describe what this policy protects"/></Field><div className="field-grid"><Field label="Applies to"><select value={form.agentId} onChange={event=>set('agentId',event.target.value)}><option value="*">All agents</option>{agents.map(agent=><option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></Field><Field label="Action type"><input required value={form.actionType} onChange={event=>set('actionType',event.target.value)} placeholder="* or research"/></Field></div><div className="field-grid"><Field label="Resource pattern"><input value={form.resourcePattern} onChange={event=>set('resourcePattern',event.target.value)} placeholder="* or tool:browser"/></Field><Field label="Priority"><input type="number" value={form.priority} onChange={event=>set('priority',event.target.value)}/></Field></div><Field label="Policy effect"><div className="effect-options">{[['require_approval','◷','Require approval'],['block','⊘','Block'],['allow','✓','Allow']].map(([value,icon,label])=><button type="button" key={value} className={form.effect===value?'chosen':''} onClick={()=>set('effect',value)}><span>{icon}</span>{label}</button>)}</div></Field></>}
  {!isAgent&&!isPolicy&&<><Field label="Agent"><select required value={form.agentId==='*'?'':form.agentId} onChange={event=>set('agentId',event.target.value)}><option value="" disabled>Select an agent</option>{agents.map(agent=><option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></Field><Field label="Action requiring approval"><input required value={form.action||''} onChange={event=>set('action',event.target.value)} placeholder="Describe the proposed action"/></Field><Field label="Risk or reason"><textarea required value={form.risk||''} onChange={event=>set('risk',event.target.value)} placeholder="Why does this action need review?" rows="3"/></Field></>}
  </div><div className="modal-foot"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" type="submit">{isAgent?'Register agent':isPolicy?'Save policy':'Create request'}</button></div></form></div>}
function FleetWizard({agents,onClose,onComplete}){const[raw,setRaw]=useState('name,team,tools\nMarket Research Agent,Stock Operations,market-data\nNews Agent,Stock Operations,news-search');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const rows=raw.split(/\r?\n/).filter(Boolean).slice(1).map(line=>{const [name,team,tools='']=line.split(',');return{name:name?.trim(),team:team?.trim(),tools:tools.split('|').map(x=>x.trim()).filter(Boolean)}}).filter(row=>row.name);const submit=async()=>{setBusy(true);setError('');try{const result=await request('/api/agents/bulk',{method:'POST',body:JSON.stringify({agents:rows})});if(result.rejected?.length)throw new Error(`${result.rejected.length} rows rejected`);await onComplete()}catch(err){setError(err.message)}finally{setBusy(false)}};return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="modal fleet-modal"><div className="modal-head"><div><span className="eyebrow">NO-CODE ONBOARDING</span><h2>Connect your agent fleet</h2></div><button className="close-button" onClick={onClose}>×</button></div><div className="modal-body"><p className="fleet-help">Paste a CSV list of agents. AgentGuard will generate IDs and onboard the entire fleet in one step.</p><Field label="Agent list" hint="Columns: name, team, tools (separate tools with |)"><textarea rows="8" value={raw} onChange={event=>setRaw(event.target.value)} /></Field><div className="fleet-preview"><b>{rows.length} agents ready to connect</b>{rows.slice(0,5).map((row,index)=><span key={index}>{row.name} · {row.team||'Unassigned'}</span>)}</div>{error&&<div className="error-banner">{error}</div>}</div><div className="modal-foot"><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy||!rows.length} onClick={submit}>{busy?'Connecting…':'Connect fleet'}</button></div></section></div>}
function EditAgentDialog({agent,agents,companies,onClose,onSaved}){const[form,setForm]=useState({companyId:agent.companyId||'default',name:agent.name,team:agent.team,tools:(agent.tools||[]).join(','),parentId:agent.parentId||'',runtimeUrl:agent.connection?.runtimeUrl||''});const[busy,setBusy]=useState(false);const save=async event=>{event.preventDefault();setBusy(true);try{await request(`/api/agents/${encodeURIComponent(agent.id)}`,{method:'PATCH',body:JSON.stringify({...form,parentId:form.parentId||null,tools:form.tools.split(',').map(x=>x.trim()).filter(Boolean)})});await onSaved()}finally{setBusy(false)}};const parents=agents.filter(item=>item.id!==agent.id&&item.companyId===form.companyId);const setCompany=companyId=>setForm({...form,companyId,parentId:parents.some(parent=>parent.id===form.parentId)?form.parentId:''});return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">AGENT CONFIGURATION</span><h2>Edit {agent.name}</h2></div><button type="button" className="close-button" onClick={onClose}>×</button></div><div className="modal-body"><Field label="Agent ID" hint="Permanent system-generated identifier"><input value={agent.id} readOnly /></Field><Field label="Company name"><select required value={form.companyId} onChange={e=>setCompany(e.target.value)}>{companies.map(company=><option key={company.id} value={company.id}>{company.name}</option>)}</select></Field><Field label="Agent name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Team or owner"><input required value={form.team} onChange={e=>setForm({...form,team:e.target.value})}/></Field><Field label="Agent API URL"><input type="url" value={form.runtimeUrl} onChange={e=>setForm({...form,runtimeUrl:e.target.value})} placeholder="http://localhost:8000/api/agentguard/connect"/></Field><Field label="Parent agent" hint="Only agents in the selected company can be parents"><select value={form.parentId} onChange={e=>setForm({...form,parentId:e.target.value})}><option value="">Standalone agent</option>{parents.map(parent=><option key={parent.id} value={parent.id}>{parent.name} · {parent.id}</option>)}</select></Field><Field label="Connected tools" hint="Comma-separated"><input value={form.tools} onChange={e=>setForm({...form,tools:e.target.value})}/></Field></div><div className="modal-foot"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form></div>}
function ConnectionDialog({agent,onClose,onConnected}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[credential,setCredential]=useState('');const connected=agent.status==='healthy'&&agent.connection?.mode==='gateway';const activate=async()=>{setBusy(true);setError('');try{const result=await request(`/api/agents/${encodeURIComponent(agent.id)}/credentials`,{method:'POST',body:'{}'});setCredential(result.gatewayCredential)}catch(err){setError(err.message)}finally{setBusy(false)}};const stop=async()=>{setBusy(true);try{await request(`/api/agents/${encodeURIComponent(agent.id)}/connection/stop`,{method:'POST',body:'{}'});await onConnected(`${agent.name} disconnected`)}catch(err){setError(err.message)}finally{setBusy(false)}};const copy=()=>navigator.clipboard?.writeText(credential);return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="modal"><div className="modal-head"><div><span className="eyebrow">AGENT GATEWAY</span><h2>{connected?'Manage':'Start'} {agent.name}</h2></div><button className="close-button" onClick={onClose}>×</button></div><div className="modal-body"><div className={`onboarding-status ${connected?'':'pending'}`}><span>{connected?'✓':'▶'}</span><div><b>{connected?'Telemetry is connected':credential?'Gateway identity activated':'Ready to activate'}</b><small>{agent.companyId||'default'} · {agent.id} · framework independent</small></div><i/></div>{credential?<><p className="connection-help">Copy this one-time credential into the company adapter or sidecar. It can report this agent only.</p><pre>{credential}</pre><button className="button secondary" onClick={copy}>Copy credential</button><div className="gateway-config"><code>AGENTGUARD_URL={location.origin}</code><code>AGENTGUARD_COMPANY_ID={agent.companyId||'default'}</code><code>AGENTGUARD_AGENT_ID={agent.id}</code></div></>:<p className="connection-help">Start creates a company-scoped gateway identity. The agent becomes Connected only after its first authenticated heartbeat, event, or OpenTelemetry trace arrives.</p>}{error&&<div className="error-banner"><span>{error}</span></div>}</div><div className="modal-foot"><button className="button secondary" onClick={onClose}>{credential?'Close':'Cancel'}</button>{connected?<button className="button secondary danger" disabled={busy} onClick={stop}>{busy?'Stopping…':'Stop connection'}</button>:credential?<button className="button primary" onClick={()=>onConnected(`${agent.name} gateway activated; awaiting telemetry`)}>Done</button>:<button className="button primary" disabled={busy} onClick={activate}>{busy?'Creating identity…':'▶ Activate gateway'}</button>}</div></section></div>}
function ManagedConnectionDialog({agent,onClose,onConnected}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');const managed=Boolean(agent.connection?.runtimeUrl);const activate=async()=>{setBusy(true);setError('');try{if(managed){await request(`/api/agents/${encodeURIComponent(agent.id)}/connection/start`,{method:'POST',body:'{}'});await onConnected(`${agent.name} connected`)}else{await request(`/api/agents/${encodeURIComponent(agent.id)}/credentials`,{method:'POST',body:'{}'});await onConnected(`${agent.name} gateway activated; awaiting telemetry`)}}catch(err){setError(err.message)}finally{setBusy(false)}};return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><div><span className="eyebrow">AGENT GATEWAY</span><h2>Start {agent.name}</h2></div><button className="close-button" onClick={onClose}>×</button></div><div className="modal-body"><div className="onboarding-status pending"><span>▶</span><div><b>Ready to activate</b><small>{agent.companyId||'default'} · {agent.id}</small></div></div><p className="connection-help">{managed?'AgentGuard will query the configured runtime URL and capture its JSON snapshot.':'AgentGuard will activate the gateway identity and await telemetry.'}</p>{error&&<div className="error-banner">{error}</div>}</div><div className="modal-foot"><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy} onClick={activate}>{busy?'Connecting…':'▶ Start connection'}</button></div></section></div>}
function Field({label,hint,children}){return <label className="field"><span>{label}{hint&&<small>{hint}</small>}</span>{children}</label>}
function Onboarding({agent,onClose}){const copy=()=>navigator.clipboard?.writeText(agent.gatewayCredential||'');return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><div className="modal onboarding-modal"><div className="modal-head"><div><span className="eyebrow">AGENT REGISTRY</span><h2>{agent.name} is registered</h2></div><button className="close-button" onClick={onClose}>×</button></div><div className="onboarding-body"><div className="onboarding-status"><span>✓</span><div><b>Company-scoped identity created</b><small>{agent.companyId} · {agent.id}</small></div><i/></div>{agent.gatewayCredential&&<><p>Copy this credential now. It is shown only once and authenticates telemetry for this agent.</p><pre>{agent.gatewayCredential}</pre><button className="button secondary" onClick={copy}>Copy gateway credential</button></>}<p>The agent becomes Connected after its first authenticated heartbeat, event, or OpenTelemetry trace reaches the gateway.</p></div><div className="modal-foot"><button className="button primary" onClick={onClose}>Done</button></div></div></div>}
function timeAgo(value){if(!value)return 'Unknown time';const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return 'Just now';if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`}

createRoot(document.getElementById('root')).render(<App/>);
